sudo: false

env:
  global:
    - GOPATH=~/gopath
    - PATH=${GOPATH}/bin:$PATH
    - NODE_VERSION="10.13.0"
    - RUBY_VERSION=2.1.1
    - GO111MODULE=on

matrix:
  allow_failures:
    - os: osx
  include:
  - os: linux
    addons:
      apt:
        packages:
          - rpm
          - gcc-mingw-w64
          - aarch64-linux-gnu-gcc
    language: go
    go: "1.11"
  - os: osx
    osx_image: xcode8.3
    language: go
    go: "1.11"

before_install:
- nvm install ${NODE_VERSION}
- nvm use ${NODE_VERSION}

script:
- |
  make install-deps || exit 1
  make dist || exit 1

  # On Linux, make a Windows/ARM64 release as well.
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    GOOS=windows CC=x86_64-w64-mingw32-gcc make dist || exit 1
    env GOARCH=arm64 GOARM=6 CC=aarch64-linux-gnu-gcc make dist || exit 1
  fi

  # Copy just what we want to deploy to S3 into a deploy directory, as
  # the S3 deployment step will copy everything in the directory
  # pointed at.
  mkdir -p deploy
  cp dist/*.zip deploy/

  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    rvm install $RUBY_VERSION
    rvm use $RUBY_VERSION
    gem install fpm
    sudo apt-get -y install rpm
    make deb
    make rpm
    cp dist/*.deb deploy/
    cp dist/*.rpm deploy/
  fi

deploy:
  - provider: s3
    access_key_id:
      secure: c9kbS3NW5xLKDkwxYeWLIi3ViTQTwsLLAFEQ6i+o4/2AbvYPP7V1ZGVkBNtdyEXFl9WcDRYYHnZ5CnxmjRUhrDo0/8qvtKd5j/PaidAmKH1l4cxN5mXcjmxpuw5sc8qG4wWwcDSWfcSiaOi5jbSToGERwvVp+/NnyXu6QZnb4Pg=
    secret_access_key:
      secure: c13Dhchou1/E8TpZ6X4HuQyhA++hoKinf2Z/AVOQ+yGsEr6vphwu0MpP8TwoSXmMuhUPqv0r5Ajk+vKLX064Cxfb2GpQ2KZSgyROxrBoed6l2mKLe0r1+L7ozoyr9wNeGM4x3d/JiKZJJ18DF687wv2PhDPZISM6MEEUguuueSE=
    bucket: ci-artifacts.evebox.org
    skip_cleanup: true
    region: us-west-1
    local_dir: deploy
    on:
      repo: jasonish/evebox
      branch: master
    acl: public_read
    upload-dir: master
  - provider: s3
    access_key_id:
      secure: c9kbS3NW5xLKDkwxYeWLIi3ViTQTwsLLAFEQ6i+o4/2AbvYPP7V1ZGVkBNtdyEXFl9WcDRYYHnZ5CnxmjRUhrDo0/8qvtKd5j/PaidAmKH1l4cxN5mXcjmxpuw5sc8qG4wWwcDSWfcSiaOi5jbSToGERwvVp+/NnyXu6QZnb4Pg=
    secret_access_key:
      secure: c13Dhchou1/E8TpZ6X4HuQyhA++hoKinf2Z/AVOQ+yGsEr6vphwu0MpP8TwoSXmMuhUPqv0r5Ajk+vKLX064Cxfb2GpQ2KZSgyROxrBoed6l2mKLe0r1+L7ozoyr9wNeGM4x3d/JiKZJJ18DF687wv2PhDPZISM6MEEUguuueSE=
    bucket: ci-artifacts.evebox.org
    skip_cleanup: true
    region: us-west-1
    local_dir: deploy
    on:
      repo: jasonish/evebox
      branch: develop
    acl: public_read
    upload-dir: develop
  - provider: s3
    access_key_id:
      secure: c9kbS3NW5xLKDkwxYeWLIi3ViTQTwsLLAFEQ6i+o4/2AbvYPP7V1ZGVkBNtdyEXFl9WcDRYYHnZ5CnxmjRUhrDo0/8qvtKd5j/PaidAmKH1l4cxN5mXcjmxpuw5sc8qG4wWwcDSWfcSiaOi5jbSToGERwvVp+/NnyXu6QZnb4Pg=
    secret_access_key:
      secure: c13Dhchou1/E8TpZ6X4HuQyhA++hoKinf2Z/AVOQ+yGsEr6vphwu0MpP8TwoSXmMuhUPqv0r5Ajk+vKLX064Cxfb2GpQ2KZSgyROxrBoed6l2mKLe0r1+L7ozoyr9wNeGM4x3d/JiKZJJ18DF687wv2PhDPZISM6MEEUguuueSE=
    bucket: ci-artifacts.evebox.org
    skip_cleanup: true
    region: us-west-1
    local_dir: deploy
    on:
      repo: jasonish/evebox
      branch: release-staging
    acl: public_read
    upload-dir: release-staging
  - provider: s3
    access_key_id:
      secure: c9kbS3NW5xLKDkwxYeWLIi3ViTQTwsLLAFEQ6i+o4/2AbvYPP7V1ZGVkBNtdyEXFl9WcDRYYHnZ5CnxmjRUhrDo0/8qvtKd5j/PaidAmKH1l4cxN5mXcjmxpuw5sc8qG4wWwcDSWfcSiaOi5jbSToGERwvVp+/NnyXu6QZnb4Pg=
    secret_access_key:
      secure: c13Dhchou1/E8TpZ6X4HuQyhA++hoKinf2Z/AVOQ+yGsEr6vphwu0MpP8TwoSXmMuhUPqv0r5Ajk+vKLX064Cxfb2GpQ2KZSgyROxrBoed6l2mKLe0r1+L7ozoyr9wNeGM4x3d/JiKZJJ18DF687wv2PhDPZISM6MEEUguuueSE=
    bucket: ci-artifacts.evebox.org
    skip_cleanup: true
    region: us-west-1
    local_dir: deploy
    on:
      repo: jasonish/evebox
      branch: release
    acl: public_read
    upload-dir: release
